#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Routes User Controller

user:
  path: /user
  controller: App\Controller\UserController::index
  methods: [POST]

createuser:
  path: /user/create
  controller: App\Controller\UserController::createUser
  methods: [POST]

login:
  path: /user/login
  controller: App\Controller\UserController::login
  methods: [POST]

user_edit:
  path: /user/edit
  controller: App\Controller\UserController::edit
  methods: [PUT]

# Routes Machines Controller

machines:
  path: /machines
  controller: App\Controller\MachinesController::index

newmachine:
  path: /machines/new
  controller: App\Controller\MachinesController::newMachine
  methods: [POST]

my_list_machine:
  path: /machines/mylistmachine
  controller: App\Controller\MachinesController::myListMachine
  methods: [GET]
